"""
08_shap_interpretation.py

SHAP-based model interpretation.

Purpose:
    Explain how individual predictors contribute to
    predictions generated by the final machine-learning model.

Important:
    - SHAP describes model attribution patterns.
    - SHAP does NOT establish causal relationships.
    - Interpretation is performed after model training.
    - No model parameters are updated.

Outputs:
    - Global feature importance
    - SHAP contribution matrix
    - Feature dependence data
    - Individual prediction explanations

"""



import numpy as np
import pandas as pd

import shap



# ==========================================================
# 1. Calculate SHAP values
# ==========================================================


def calculate_shap_values(
        model,
        X_data
):

    """
    Calculate SHAP values for trained model.

    Parameters
    ----------
    model:
        Final trained model.

    X_data:
        Dataset for interpretation.

    Returns
    -------
    shap_values
    """


    explainer = shap.Explainer(

        model,

        X_data

    )


    shap_values = explainer(

        X_data

    )


    return shap_values




# ==========================================================
# 2. Global SHAP importance
# ==========================================================


def calculate_global_importance(

        shap_values,

        X_data

):

    """
    Calculate global feature importance.

    Importance is based on mean absolute SHAP value.

    """



    importance = pd.DataFrame(

        {

            "Feature":

                X_data.columns,


            "Mean_abs_SHAP":

                np.abs(

                    shap_values.values

                ).mean(

                    axis=0

                )

        }

    )


    importance = (

        importance

        .sort_values(

            by="Mean_abs_SHAP",

            ascending=False

        )

        .reset_index(drop=True)

    )


    return importance




# ==========================================================
# 3. SHAP contribution matrix
# ==========================================================


def generate_shap_matrix(

        shap_values,

        X_data

):

    """
    Generate observation-level SHAP contribution table.

    """



    shap_matrix = pd.DataFrame(

        shap_values.values,

        columns=X_data.columns,

        index=X_data.index

    )


    return shap_matrix




# ==========================================================
# 4. Feature dependence analysis
# ==========================================================


def generate_dependence_data(

        feature_name,

        X_data,

        shap_values

):

    """
    Generate feature-specific SHAP dependence data.

    Used for visualization of:

        feature value
        versus
        SHAP contribution


    """



    dependence = pd.DataFrame(

        {

            "Feature_value":

                X_data[feature_name],


            "SHAP_value":

                shap_values[:, feature_name].values

        }

    )


    return dependence




# ==========================================================
# 5. Individual prediction explanation
# ==========================================================


def individual_prediction_explanation(

        shap_values,

        index

):

    """
    Extract SHAP contribution for
    an individual prediction.

    """



    explanation = pd.DataFrame(

        {

            "Feature":

                shap_values.feature_names,


            "SHAP_contribution":

                shap_values[index].values

        }

    )


    explanation["absolute_contribution"] = (

        np.abs(

            explanation["SHAP_contribution"]

        )

    )


    explanation = (

        explanation

        .sort_values(

            by="absolute_contribution",

            ascending=False

        )

    )


    return explanation




# ==========================================================
# 6. High-risk prediction explanation
# ==========================================================


def classify_prediction_group(

        probability,

        threshold

):

    """
    Categorize prediction according to
    predefined threshold.

    Threshold should be obtained from
    development cohort.

    """

    if probability >= threshold:

        return "Higher predicted risk"

    else:

        return "Lower predicted risk"




# ==========================================================
# 7. Export interpretation results
# ==========================================================


def export_shap_results(

        model,

        X_data

):

    """
    Complete SHAP interpretation workflow.

    """


    shap_values = calculate_shap_values(

        model,

        X_data

    )


    importance = calculate_global_importance(

        shap_values,

        X_data

    )


    matrix = generate_shap_matrix(

        shap_values,

        X_data

    )


    return {

        "shap_values":

            shap_values,


        "global_importance":

            importance,


        "shap_matrix":

            matrix

    }




if __name__ == "__main__":


    print(

        """

        SHAP interpretation module.

        Workflow:

        Trained final model
                |
                v
        SHAP explanation
                |
                v
        Feature contribution analysis


        Interpretation:

        SHAP values represent model-attribution
        patterns and predictive associations,
        not causal effects.


        """

    )